import lunch1 from '../images/lunch1.png';
import lunch2 from '../images/lunch2.png';
import lunch3 from '../images/lunch3.png';
import lunch4 from '../images/lunch4.png';
import lunch5 from '../images/lunch5.png';
import lunch6 from '../images/lunch6.png';
const allFoods = [
    { 
        id: 1,
        name: 'Healthy Meal Plan',
        excerpt: 'How we dream about our future',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque massa mi, imperdiet nec mattis a, vestibulum ut mauris. Proin iaculis tortor vitae ipsum feugiat hendrerit. Cras dapibus vulputate lobortis. Nunc tincidunt nisi non quam cursus varius. Cras in dui molestie, sodales tortor id.',
        price: 100.99,
        category: 'lunch',
        image: lunch1,
    },
    { 
        id: 2,
        name: 'Fride Chiken Bento',
        excerpt: 'How we dream about our future',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque massa mi, imperdiet nec mattis a, vestibulum ut mauris. Proin iaculis tortor vitae ipsum feugiat hendrerit. Cras dapibus vulputate lobortis. Nunc tincidunt nisi non quam cursus varius. Cras in dui molestie, sodales tortor id.',
        price: 9.99,
        category: 'lunch',
        image: lunch2,
    },
    { 
        id: 3,
        name: 'Tarragon-Rubbed-Salmon',
        excerpt: 'How we dream about our future',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque massa mi, imperdiet nec mattis a, vestibulum ut mauris. Proin iaculis tortor vitae ipsum feugiat hendrerit. Cras dapibus vulputate lobortis. Nunc tincidunt nisi non quam cursus varius. Cras in dui molestie, sodales tortor id.',
        price: 6.99,
        category: 'lunch',
        image: lunch3,
    },
    { 
        id: 4,
        name: 'Indian Lunch',
        excerpt: 'How we dream about our future',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque massa mi, imperdiet nec mattis a, vestibulum ut mauris. Proin iaculis tortor vitae ipsum feugiat hendrerit. Cras dapibus vulputate lobortis. Nunc tincidunt nisi non quam cursus varius. Cras in dui molestie, sodales tortor id.',
        price: 8.99,
        category: 'lunch',
        image: lunch4,
    },
    { 
        id: 5,
        name: 'Beef Steak',
        excerpt: 'How we dream about our future',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque massa mi, imperdiet nec mattis a, vestibulum ut mauris. Proin iaculis tortor vitae ipsum feugiat hendrerit. Cras dapibus vulputate lobortis. Nunc tincidunt nisi non quam cursus varius. Cras in dui molestie, sodales tortor id.',
        price: 15.99,
        category: 'lunch',
        image: lunch5,
    },
    { 
        id: 6,
        name: 'Honey-Soy-Glazed Salmon',
        excerpt: 'How we dream about our future',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque massa mi, imperdiet nec mattis a, vestibulum ut mauris. Proin iaculis tortor vitae ipsum feugiat hendrerit. Cras dapibus vulputate lobortis. Nunc tincidunt nisi non quam cursus varius. Cras in dui molestie, sodales tortor id.',
        price: 7.99,
        category: 'lunch',
        image: lunch6,
    },
    { 
        id: 7,
        name: 'This is Breakfast Food',
        excerpt: 'How we dream about our future',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque massa mi, imperdiet nec mattis a, vestibulum ut mauris. Proin iaculis tortor vitae ipsum feugiat hendrerit. Cras dapibus vulputate lobortis. Nunc tincidunt nisi non quam cursus varius. Cras in dui molestie, sodales tortor id.',
        price: 7.99,
        category: 'breakfast',
        image: lunch6,
    },
    { 
        id: 8,
        name: 'Breakfast Food 2',
        excerpt: 'How we dream about our future',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque massa mi, imperdiet nec mattis a, vestibulum ut mauris. Proin iaculis tortor vitae ipsum feugiat hendrerit. Cras dapibus vulputate lobortis. Nunc tincidunt nisi non quam cursus varius. Cras in dui molestie, sodales tortor id.',
        price: 23.99,
        category: 'breakfast',
        image: lunch5,

    },
    { 
        id: 9,
        name: 'Breakfast Food 3',
        excerpt: 'How we dream about our future',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque massa mi, imperdiet nec mattis a, vestibulum ut mauris. Proin iaculis tortor vitae ipsum feugiat hendrerit. Cras dapibus vulputate lobortis. Nunc tincidunt nisi non quam cursus varius. Cras in dui molestie, sodales tortor id.',
        price: 12.99,
        category: 'breakfast',
        image: lunch4,
    },
    { 
        id: 10,
        name: 'Breakfast Food 4',
        excerpt: 'How we dream about our future',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque massa mi, imperdiet nec mattis a, vestibulum ut mauris. Proin iaculis tortor vitae ipsum feugiat hendrerit. Cras dapibus vulputate lobortis. Nunc tincidunt nisi non quam cursus varius. Cras in dui molestie, sodales tortor id.',
        price: 13.99,
        category: 'breakfast',
        image: lunch3,
    },
    { 
        id: 11,
        name: 'Breakfast Food 5',
        excerpt: 'How we dream about our future',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque massa mi, imperdiet nec mattis a, vestibulum ut mauris. Proin iaculis tortor vitae ipsum feugiat hendrerit. Cras dapibus vulputate lobortis. Nunc tincidunt nisi non quam cursus varius. Cras in dui molestie, sodales tortor id.',
        price: 16.99,
        category: 'breakfast',
        image: lunch2,
    },
    { 
        id: 12,
        name: 'Breakfast Food 6',
        excerpt: 'How we dream about our future',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque massa mi, imperdiet nec mattis a, vestibulum ut mauris. Proin iaculis tortor vitae ipsum feugiat hendrerit. Cras dapibus vulputate lobortis. Nunc tincidunt nisi non quam cursus varius. Cras in dui molestie, sodales tortor id.',
        price: 38.99,
        category: 'breakfast',
        image: lunch1,
    },
    { 
        id: 13,
        name: 'Dinner Food 1',
        excerpt: 'How we dream about our future',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque massa mi, imperdiet nec mattis a, vestibulum ut mauris. Proin iaculis tortor vitae ipsum feugiat hendrerit. Cras dapibus vulputate lobortis. Nunc tincidunt nisi non quam cursus varius. Cras in dui molestie, sodales tortor id.',
        price: 50.99,
        category: 'dinner',
        image: lunch3,
    },
    { 
        id: 14,
        name: 'Dinner Food 2',
        excerpt: 'How we dream about our future',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque massa mi, imperdiet nec mattis a, vestibulum ut mauris. Proin iaculis tortor vitae ipsum feugiat hendrerit. Cras dapibus vulputate lobortis. Nunc tincidunt nisi non quam cursus varius. Cras in dui molestie, sodales tortor id.',
        price: 45.99,
        category: 'dinner',
        image: lunch6,
    },
    { 
        id: 15,
        name: 'Dinner Food 3',
        excerpt: 'How we dream about our future',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque massa mi, imperdiet nec mattis a, vestibulum ut mauris. Proin iaculis tortor vitae ipsum feugiat hendrerit. Cras dapibus vulputate lobortis. Nunc tincidunt nisi non quam cursus varius. Cras in dui molestie, sodales tortor id.',
        price: 27.99,
        category: 'dinner',
        image: lunch2,
    },
    { 
        id: 16,
        name: 'Dinner Food 4',
        excerpt: 'How we dream about our future',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque massa mi, imperdiet nec mattis a, vestibulum ut mauris. Proin iaculis tortor vitae ipsum feugiat hendrerit. Cras dapibus vulputate lobortis. Nunc tincidunt nisi non quam cursus varius. Cras in dui molestie, sodales tortor id.',
        price: 35.99,
        category: 'dinner',
        image: lunch1,
    },
    { 
        id: 17,
        name: 'Dinner Food 5',
        excerpt: 'How we dream about our future',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque massa mi, imperdiet nec mattis a, vestibulum ut mauris. Proin iaculis tortor vitae ipsum feugiat hendrerit. Cras dapibus vulputate lobortis. Nunc tincidunt nisi non quam cursus varius. Cras in dui molestie, sodales tortor id.',
        price: 75.99,
        category: 'dinner',
        image: lunch6,
    },
    { 
        id: 18,
        name: 'Dinner Food 6',
        excerpt: 'How we dream about our future',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque massa mi, imperdiet nec mattis a, vestibulum ut mauris. Proin iaculis tortor vitae ipsum feugiat hendrerit. Cras dapibus vulputate lobortis. Nunc tincidunt nisi non quam cursus varius. Cras in dui molestie, sodales tortor id.',
        price: 62.99,
        category: 'dinner',
        image: lunch4,
    },

]

export default allFoods;